/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.grgit.example;

import java.io.File;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class LibraryTest {
    @Test 
    void testSomeLibraryMethod() {
        File testFile = new File("data/test/test.txt");
        Assertions.assertTrue(testFile.exists());
    }
}
